### ISSUE TITLE
Refactor BIDS tracker

### ISSUE THREAD

**Issue by michellewang** [neurodatascience/nipoppy#93]
The current [`bids_tracker.py` ](https://github.com/neurodatascience/mr_proc/blob/f4682b400f82c101149281346f4e25a8fc5b0aad/trackers/bids_tracker.py) is very old and needs a big update.

- [ ] Use manifest to know which participants/sessions to track
- [ ] Check BIDS datatype (`anat`, `dwi`, `func`, etc.)
- [ ] Check BIDS suffix (`T1w`, etc.)

@nikhil153 I think we should be able to make a `tracker_configs` dictionary like for the derivatives trackers. It's just that the column names in the bagel will have to be `HAS_DATATYPE__<...>` and `HAS_IMAGE__<...>` instead of `pipeline_complete`/`PHASE__<...>`/`STAGE__<...>` (and the values will be `True`/`False` instead of `SUCCESS`/`FAIL`/`UNAVAILABLE`)

**Comment by michellewang** [comment]
@nikhil153 I discussed with @alyssadai  today how to combine the `HAS_DATATYPE__` / `HAS_IMAGE__` information with the derivatives bagel so that the dashboard can display everything at the same time. Do you think it would make sense to run the BIDS tracker every time the derivatives tracker is run? This would ensure that we have the latest information for both the BIDS and the derivatives directories. But the obvious downside is that it can take a long time to run the trackers. Maybe parallelization can help speed things up?
